# Generated by Django 3.2.6 on 2021-11-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodinput',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
