# Generated by Django 3.2.6 on 2021-11-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0002_moodinput_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodinput',
            name='streak',
            field=models.IntegerField(default=1),
        ),
    ]
