# Generated by Django 3.2.6 on 2021-11-26 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moodtracker', '0003_alter_moodinput_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodinput',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moodinputs', to=settings.AUTH_USER_MODEL),
        ),
    ]
